pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
    actions:
      merge:
        method: merge
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge
merge_protections_settings:
  reporting_method: check-runs
