tools:
  php_code_sniffer:
    config:
      standard: WordPress
  sensiolabs_security_checker: true
checks:
  php:
    avoid_closing_tag: false
    avoid_superglobals: false
    coding_standard:
      name: WordPress
    no_exit: false
    no_global_keyword: false
    one_class_per_file: false
    psr2_class_declaration: false
    psr2_control_structure_declaration: false
    psr2_switch_declaration: false
    variable_existence: false
    verify_access_scope_valid: false
    verify_argument_usable_as_reference: false
    verify_property_names: false
filter:
    dependency_paths:
        - wordpress/
    excluded_paths: [tests/*, bin/*, assets/*, languages/*, includes/classes/legacy/*, vendor/*]
build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.4
      services:
        mariadb: 10
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - js-scrutinizer-run
          - command: phpcs-run -p -s -v -n --standard=./.phpcs.xml --extensions=php --ignore=*/wordpress/*
      dependencies:
        before:
          - composer require --dev johnpbloch/wordpress